import { SessionProvider } from 'next-auth/react';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';
import { Analytics } from '@vercel/analytics/react';

import { Toaster } from '@/components/ui/sonner';
import Providers from '@/components/providers/providers';
import { auth } from '@/auth';

const font = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'ImaginAItion',
  description: 'Generated by create next app'
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={font.className}>
          <Providers>
            {children}
          </Providers>

          <Toaster />
          <Analytics />
        </body>
      </html>
    </SessionProvider>
  );
}
